#Title: config.py
#Author: Timothy Damir Kovacic
#API KEY DETAILS FOR CLIENT CONNECTION TO YOUR COINBASE PRO ACCOUNT
API_KEY=""
API_SEC=""
API_PHR=""

#FIAT BASED COIN-PAIR FROM COINBASE PRO LISTINGS (ALWAYS IN [COIN]-[FIAT] FORMAT)
MARKET="ADA-USD"
#THE COINBASE PRO ID FOR YOUR SELECTED COIN
COIN_ID=""
#THE COINBASE PRO ID FOR YOUR SELECTED FIAT
FIAT_ID=""

#THE SECONDS IT TAKES THIS TOOL REFRESH
SEC_INTERVAL="60"
#THE INTERVALS IT TAKES FOR THIS TOOL TO AUTO-SAVE IT'S DATA
SAVE_INTERVAL="15"
#THE MAX LENGTH OF THE CHART (MAX CHARTED INTERVALS)
CHART_LENGTH="60"
#THE DISTANCE BETWEEN BUY / SELL POINTS FROM YESTERDAY'S OPENING PRICE CALLED DELEGATION LEVELS
DELEGATION_LEVEL="0.025"
#THE MAX VOLUME OF COIN THAT WILL BE BOUGHT OR SOLD ON BOTH ENDS OF DELEGATION LEVELS
TRADE_VOLUME="10"
#THE PERCENTAGE (VALUE BETWEEN 0 AND 1) OF THE SELL VOLUME THAT IS WITHELD FROM BEGIN SOLD
RETRACTION_RATE="0.5"
#WHEN COST DOLLAR AVERAGING MODE IS ACTIVE THE PROGRAM WILL NOT SELL (1 = ACTIVE, 0 = INACTIVE)
CDA_MODE=0
#WHEN DYNAMIC CLIMBING MODE IS ACTIVE THE PROGRAM WILL REPLACE YSP WITH DCP ON INTERVAL AND MAX DELEGATION LEVELS (1 = ACTIVE, 0 = INACTIVE)
DC_MODE=0
#THE INTERVALS IT TAKES FOR THE YSP TO BE RESET TO CURRENT PRICE
DCP_INTERVAL="720"
